version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 3
    package-ecosystem: "pip"
    reviewers:
      - "harrystech/data-platform"
    schedule:
      day: "tuesday"
      interval: "weekly"
