[tool.black]
include = '\.pyi?$'
line-length = 100
target-version = ['py38']

[tool.isort]
combine_star = true
default_section = "THIRDPARTY"
include_trailing_comma = true
force_grid_wrap = 0
known_first_party = ["src", "tests"]
line_length = 100
multi_line_output = 3
use_parentheses = true
