service: CloudWatchLogsToElasticsearch

custom:
  elasticsearchDomainName: ${env:ES_DOMAIN_NAME, "dw-es-dev"}
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}

provider:
  name: aws
  runtime: python3.8

  region: ${self:custom.region}
  stage: ${self:custom.stage}

  iamRoleStatements:
    - Action: es:DescribeElasticsearchDomain
      Effect: Allow
      Resource: arn:aws:es:*:*:domain/${self:custom.elasticsearchDomainName}
      Sid: DescribeElasticsearchDomain
    - Action: es:ESHttp*
      Effect: Allow
      Resource: arn:aws:es:*:*:domain/${self:custom.elasticsearchDomainName}/*
      Sid: AccessToElasticsearchDomain
  versionFunctions: true

package:
  individually: true
  exclude:
    - "./**"

functions:
  lambdaHandler:
    environment:
      ES_DOMAIN_NAME: ${self:custom.elasticsearchDomainName}
    handler: cw_logs_to_es.lambda_handler.process
    memorySize: 512  # in MB
    timeout: 360  # in seconds
    package:
      include:
        - cw_logs_to_es/**
        - certifi/**
        - chardet/**
        - elasticsearch/**
        - idna/**
        - requests/**
        - requests_aws4auth/**
        - urllib3/**

resources:
  extensions:
    LambdaHandlerLogGroup:
      Properties:
        RetentionInDays: "30"
