version: 2.1

jobs:
  test:
    working_directory: /home/circleci/js-sdk
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    working_directory: /home/circleci/js-sdk
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/js-sdk/.npmrc
      - run:
          name: Compile Source
          command: yarn run compile
      - run:
          name: Publish Package
          command: npm publish
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          context:
            - npm-procore-private-automation
          filters:
            branches:
              only:
                - master
