version: 2.1
executors:
  sonar-scanner:
    docker:
      - image: sonarsource/sonar-scanner-cli:4.7.0
jobs:
  test:
    working_directory: ~/js-sdk
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Test
          command: yarn test
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish:
    working_directory: ~/js-sdk
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/js-sdk/.npmrc
      - run:
          name: Compile Source
          command: yarn run compile
      - run:
          name: Publish Package
          command: npm publish
  sonarqube_analysis:
    working_directory: /home/circleci/app
    executor: sonar-scanner
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Execute sonar-scanner
          command: sonar-scanner -Dsonar.host.url=$SONARQUBE_HOST -Dsonar.login=$SONARQUBE_OPS_CI_TOKEN -Dsonar.buildString=$CIRCLE_SHA1 -Dsonar.analysis.build.url=$CIRCLE_BUILD_URL
workflows:
  version: 2
  test_and_publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          context:
            - npm-procore-private-automation
          filters:
            branches:
              only:
                - master
      - sonarqube_analysis:
          context: procore-sonarqube-ci
          requires:
            - test
