name: Node.js Inspection Pipeline

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20, 21 ]

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Running ESLint...
      run: npm run pretest

    - name: Running tests...
      run: npm test

    - name: Upload coverage to Codecov 
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage

