name: Run pre-commit hooks against all files

on:
  push:
    paths:
    - ".github/workflows/pre-commit.yaml"
    - "cloudwatch_logs/**"
    - "json_logging/**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
