name: Test
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: ['3.0', '3.1', '3.2']
        include:
          - os: ubuntu-20.04
            ruby: '2.7'
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:14.8-bullseye
        env:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: handcuffs_test
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      PGHOST: localhost
      PGUSER: ubuntu
      RAILS_ENV: test
      BUNDLER_VERSION: 1.17.3
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ env.BUNDLER_VERSION }}
          bundler-cache: true
      - name: Installing dependencies
        run: bundle install && cd spec/dummy && bundle install
      - name: Install Apprasals Dependencies
        run: bundle exec appraisal install
      - name: Setup Database
        run: cd spec/dummy && bundle exec rake db:create db:migrate --trace
      - name: Run Appraisals Tests
        run: bundle exec appraisal rspec
      - name: Run Dummy App Tests
        run: cd spec/dummy && bin/rspec
