# Simple workflow to run unit tests.

name: Unit Tests

on:
  push:
    paths:
    - ".github/workflows/unittest.yaml"
    - "cloudwatch_logs/cw_logs_to_es/**"
    - "json_logging/**"

jobs:
  unittest-json-logging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run unit tests
      run: |-
        cd json_logging/
        python3 setup.py develop
        python3 -m unittest discover -v tests/
